/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#d4d3dd",
        primary: "#684cb6",
        "tertiary-fixed": "#6bffc1",
        "secondary-fixed": "#e3e1ec",
        "on-surface-variant": "#5d5e6c",
        "on-tertiary": "#e6ffef",
        "inverse-primary": "#a589f8",
        "surface-container": "#eeecfa",
        "on-secondary-container": "#515159",
        "primary-fixed-dim": "#987cea",
        "on-background": "#30323e",
        "inverse-surface": "#0d0e14",
        tertiary: "#006d4b",
        "surface-bright": "#fbf8ff",
        "on-primary-fixed": "#000000",
        "surface-tint": "#684cb6",
        surface: "#fbf8ff",
        "on-secondary-fixed": "#3e3f47",
        "on-tertiary-fixed": "#004b33",
        "on-secondary-fixed-variant": "#5a5b63",
        error: "#a8364b",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#fdf7ff",
        "error-container": "#f97386",
        "on-surface": "#30323e",
        "primary-container": "#a589f8",
        "on-error": "#fff7f7",
        "on-tertiary-container": "#006042",
        "on-error-container": "#6e0523",
        background: "#fbf8ff",
        "on-tertiary-fixed-variant": "#006b4a",
        "surface-container-high": "#e8e7f5",
        "on-primary-fixed-variant": "#2e007c",
        "outline-variant": "#b1b1c0",
        "primary-fixed": "#a589f8",
        "on-secondary": "#faf8ff",
        "surface-variant": "#e2e1f2",
        outline: "#797988",
        "inverse-on-surface": "#9d9ca4",
        "surface-container-low": "#f4f2fe",
        "secondary-container": "#e3e1ec",
        "tertiary-container": "#6bffc1",
        "surface-dim": "#d9d8e9",
        secondary: "#5e5e67",
        "surface-container-highest": "#e2e1f2",
        "on-primary-container": "#230062",
        "tertiary-fixed-dim": "#5af0b4",
        "primary-dim": "#5b3fa9",
        "tertiary-dim": "#005f41",
        "error-dim": "#6b0221",
        "secondary-dim": "#52525b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        lg: "24px",
        xs: "4px",
        gutter: "16px",
        base: "8px",
        sm: "8px",
        md: "16px",
        margin: "24px",
      },
      fontFamily: {
        "label-md": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-xl": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "body-sm": ["Montserrat", "sans-serif"],
        "label-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "display-md": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["3rem", { lineHeight: "1.1", fontWeight: "700" }],
        "display-lg": ["2.5rem", { lineHeight: "1.15", fontWeight: "700" }],
        "display-md": ["2rem", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["1.5rem", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-md": ["1.25rem", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-sm": ["1rem", { lineHeight: "1.5", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.6" }],
        "body-md": ["0.875rem", { lineHeight: "1.6" }],
        "body-sm": ["0.75rem", { lineHeight: "1.6" }],
        "label-lg": ["0.875rem", { lineHeight: "1.4", fontWeight: "500" }],
        "label-md": ["0.875rem", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm": ["0.75rem", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
